name: Build and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Import GPG private key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          gpg --list-keys

      - name: Write Maven settings.xml from secret
        run: |
          mkdir -p ~/.m2
          echo "${{ secrets.MAVEN_SETTINGS_XML }}" > ~/.m2/settings.xml

      - name: Build and deploy to Sonatype OSSRH
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          sudo apt update
          sudo apt install -y gnupg ca-certificates mono-complete
          mvn clean test -Denv=test
  
          mvn clean deploy -Prelease -DskipTests -P sign-artifacts \
              -Dgpg.executable=gpg \
              -Dgpg.passphrase="$GPG_PASSPHRASE"

